/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorNeutral0 = "#000000"; // Pure black
export const ColorNeutral50 = "#0a0a0a"; // Deepest background
export const ColorNeutral100 = "#121212"; // Primary background
export const ColorNeutral200 = "#1e1e1e"; // Card background
export const ColorNeutral300 = "#282828"; // Elevated background
export const ColorNeutral400 = "#333333"; // Hover background
export const ColorNeutral500 = "#404040"; // Default border
export const ColorNeutral600 = "#6b6b6b"; // Disabled text
export const ColorNeutral700 = "#a3a3a3"; // Secondary text
export const ColorNeutral800 = "#d4d4d4"; // Regular text
export const ColorNeutral900 = "#f5f5f5"; // Heading text
export const ColorNeutral1000 = "#ffffff"; // Pure white / Emphasis text
export const ColorBrandPrimary50 = "#e0f5f4"; // Lightest cyan
export const ColorBrandPrimary100 = "#b3e8e5";
export const ColorBrandPrimary200 = "#80dad6";
export const ColorBrandPrimary300 = "#4dccc7";
export const ColorBrandPrimary400 = "#26c1bc"; // Light cyan
export const ColorBrandPrimary500 = "#00a9a5"; // PRIMARY BRAND COLOR - Vibrant cyan
export const ColorBrandPrimary600 = "#00a19d";
export const ColorBrandPrimary700 = "#009793";
export const ColorBrandPrimary800 = "#008d89"; // Dark cyan
export const ColorBrandPrimary900 = "#007b77"; // Darkest cyan
export const ColorAccentPurple400 = "#ab47bc";
export const ColorAccentPurple500 = "#a78bfa"; // Workflow tags
export const ColorAccentPink400 = "#ec4899";
export const ColorAccentPink500 = "#f472b6"; // Note categories
export const ColorAccentAmber400 = "#fbbf24"; // Calendar highlights
export const ColorAccentAmber500 = "#f59e0b";
export const ColorSemanticSuccess50 = "#e8f5e9"; // Success background
export const ColorSemanticSuccess500 = "#10b981"; // Success state
export const ColorSemanticSuccess700 = "#059669"; // Success dark
export const ColorSemanticWarning50 = "#fff3e0"; // Warning background
export const ColorSemanticWarning500 = "#f59e0b"; // Warning state
export const ColorSemanticWarning700 = "#d97706"; // Warning dark
export const ColorSemanticError50 = "#ffebee"; // Error background
export const ColorSemanticError500 = "#ef4444"; // Error state
export const ColorSemanticError700 = "#dc2626"; // Error dark
export const ColorSemanticInfo50 = "#e3f2fd"; // Info background
export const ColorSemanticInfo500 = "#3b82f6"; // Info state
export const ColorSemanticInfo700 = "#2563eb"; // Info dark
export const RadiusNone = "0";
export const RadiusSm = "0.25rem"; // 4px
export const RadiusBase = "0.5rem"; // 8px
export const RadiusMd = "0.75rem"; // 12px
export const RadiusLg = "1rem"; // 16px
export const RadiusXl = "1.5rem"; // 24px
export const RadiusFull = "9999px";
export const ShadowNone = "none";
export const ShadowSm = "0 1px 2px 0 rgba(0, 0, 0, 0.05)";
export const ShadowBase =
  "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)";
export const ShadowMd =
  "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)";
export const ShadowLg =
  "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)";
export const ShadowXl =
  "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)";
export const Shadow2xl = "0 25px 50px -12px rgba(0, 0, 0, 0.25)";
export const ShadowInner = "inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)";
export const ShadowCard =
  "0 2px 8px rgba(0, 0, 0, 0.15), 0 0 0 1px rgba(255, 255, 255, 0.05)"; // Card hover effect
export const ShadowCardHover =
  "0 4px 16px rgba(0, 169, 165, 0.2), 0 0 0 1px rgba(0, 169, 165, 0.1)"; // Card hover with accent glow
export const Space0 = "0";
export const Space1 = "0.25rem"; // 4px
export const Space2 = "0.5rem"; // 8px
export const Space3 = "0.75rem"; // 12px
export const Space4 = "1rem"; // 16px
export const Space5 = "1.25rem"; // 20px
export const Space6 = "1.5rem"; // 24px
export const Space8 = "2rem"; // 32px
export const Space10 = "2.5rem"; // 40px
export const Space12 = "3rem"; // 48px
export const Space16 = "4rem"; // 64px
export const Space20 = "5rem"; // 80px
export const Space24 = "6rem"; // 96px
export const SizeIconXs = "0.75rem"; // 12px
export const SizeIconSm = "1rem"; // 16px
export const SizeIconMd = "1.25rem"; // 20px
export const SizeIconLg = "1.5rem"; // 24px
export const SizeIconXl = "2rem"; // 32px
export const SizeContainerSm = "640px";
export const SizeContainerMd = "768px";
export const SizeContainerLg = "1024px";
export const SizeContainerXl = "1280px";
export const SizeContainer2xl = "1536px";
export const FontFamilySans =
  "'Inter Variable', -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif";
export const FontFamilyCjk =
  "'Noto Sans SC Variable', 'PingFang SC', 'Microsoft YaHei', sans-serif";
export const FontFamilyMono =
  "'JetBrains Mono Variable', 'SF Mono', Consolas, 'Courier New', monospace";
export const FontSizeXs = "0.75rem"; // 12px
export const FontSizeSm = "0.875rem"; // 14px
export const FontSizeBase = "1rem"; // 16px
export const FontSizeLg = "1.125rem"; // 18px
export const FontSizeXl = "1.25rem"; // 20px
export const FontSize2xl = "1.5rem"; // 24px
export const FontSize3xl = "1.875rem"; // 30px
export const FontSize4xl = "2.25rem"; // 36px
export const FontSize5xl = "3rem"; // 48px
export const FontWeightLight = "300";
export const FontWeightNormal = "400";
export const FontWeightMedium = "500";
export const FontWeightSemibold = "600";
export const FontWeightBold = "700";
export const FontLineHeightTight = "1.25";
export const FontLineHeightNormal = "1.5";
export const FontLineHeightRelaxed = "1.75";
export const FontLineHeightLoose = "2";
export const FontLetterSpacingTighter = "-0.05em";
export const FontLetterSpacingTight = "-0.025em";
export const FontLetterSpacingNormal = "0";
export const FontLetterSpacingWide = "0.025em";
export const FontLetterSpacingWider = "0.05em";
export const InteractivePrimaryDefault = "#00a9a5"; // PRIMARY buttons - Cyan #00A9A5
export const InteractivePrimaryHover = "#00a19d"; // Primary hover state
export const InteractivePrimaryActive = "#009793"; // Primary active/pressed
export const InteractivePrimaryDisabled = "#404040"; // Disabled button
export const InteractiveSecondaryDefault = "#282828"; // Secondary buttons
export const InteractiveSecondaryHover = "#333333"; // Secondary hover
export const InteractiveSecondaryActive = "#404040"; // Secondary active
export const InteractiveSecondaryDisabled = "#6b6b6b"; // Disabled secondary
export const InteractiveGhostDefault = "#00000000"; // Ghost/text buttons
export const InteractiveGhostHover = "#1e1e1e"; // Ghost hover
export const InteractiveGhostActive = "#282828"; // Ghost active
export const InteractiveFocusRing = "#00a9a5"; // Focus ring color
export const InteractiveFocusRingOffset = "#121212"; // Focus ring offset
export const SurfaceBgPrimary = "#121212"; // #121212 - Primary background
export const SurfaceBgSecondary = "#1e1e1e"; // #1E1E1E - Card background
export const SurfaceBgElevated = "#282828"; // #282828 - Elevated elements
export const SurfaceBgHover = "#333333"; // #333333 - Hover background
export const SurfaceBgOverlay = "#000000"; // Modals and overlays
export const SurfaceBorderDefault = "#404040"; // #404040 - Default borders
export const SurfaceBorderSubtle = "#282828"; // Subtle dividers
export const SurfaceBorderStrong = "#6b6b6b"; // Emphasized borders
export const SurfaceBorderFocus = "#00a9a5"; // Focus rings
export const SurfaceBorderError = "#ef4444"; // Error borders
export const SurfaceInteractiveDefault = "#1e1e1e"; // Default interactive elements
export const SurfaceInteractiveHover = "#282828"; // Hover state
export const SurfaceInteractiveActive = "#333333"; // Active/pressed state
export const SurfaceInteractiveSelected = "#007b77"; // Selected state
export const TextPrimary = "#f5f5f5"; // #F5F5F5 - Headings and emphasis
export const TextSecondary = "#d4d4d4"; // #D4D4D4 - Regular text
export const TextTertiary = "#a3a3a3"; // #A3A3A3 - Secondary text
export const TextDisabled = "#6b6b6b"; // #6B6B6B - Disabled text
export const TextInverse = "#121212"; // Text on colored backgrounds
export const TextBrand = "#00a9a5"; // Brand color text
export const TextBrandHover = "#26c1bc"; // Brand color hover
export const TextSuccess = "#10b981"; // Success messages
export const TextWarning = "#f59e0b"; // Warning messages
export const TextError = "#ef4444"; // Error messages
export const TextInfo = "#3b82f6"; // Info messages
export const VnextDarkColorBg = "#121212"; // Primary background #121212
export const VnextDarkColorSurface = "#1e1e1e"; // Interactive surface
export const VnextDarkColorSurfaceHover = "#282828"; // Interactive hover
export const VnextDarkColorSurfaceActive = "#333333"; // Interactive active
export const VnextDarkColorBorder = "#404040"; // Default borders
export const VnextDarkColorBorderSubtle = "#282828"; // Subtle dividers
export const VnextDarkColorBorderAccent = "#00a9a5"; // Focus/accent borders
export const VnextDarkColorTextPrimary = "#f5f5f5"; // Primary text
export const VnextDarkColorTextSecondary = "#d4d4d4"; // Secondary text
export const VnextDarkColorTextTertiary = "#a3a3a3"; // Tertiary text
export const VnextDarkColorTextAccent = "#00a9a5"; // Brand/accent text
export const VnextDarkColorPrimary = "#00a9a5"; // Primary button
export const VnextDarkColorPrimaryHover = "#00a19d"; // Primary hover
export const VnextDarkColorPrimaryActive = "#009793"; // Primary active
