/**
 * VNext Design Tokens - Style Dictionary Configuration (ESM)
 * Generates CSS variables, TailwindCSS preset, and TypeScript types
 */

export default {
  source: [
    'tokens/src/core/**/*.json',
    'tokens/src/semantic/**/*.json',
    'tokens/src/themes/**/*.json',
  ],

  platforms: {
    // CSS Custom Properties
    css: {
      transformGroup: 'css',
      buildPath: 'src/lib/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },

    // JavaScript/TypeScript Tokens
    js: {
      transformGroup: 'js',
      buildPath: 'src/lib/tokens/',
      files: [
        {
          destination: 'index.js',
          format: 'javascript/es6',
        },
      ],
    },
  },

  hooks: {
    formats: {
      // Custom format for theme-scoped CSS variables
      'css/vnext-variables': ({ dictionary }) => {
        const tokens = dictionary.allTokens;

        const cssVars = tokens
          .map(token => `  --v-${token.path.join('-')}: ${token.value};`)
          .join('\n');

        return `/**
 * VNext Design Tokens - Dark Theme
 * Generated by Style Dictionary
 * DO NOT EDIT MANUALLY
 */

[data-theme="vnext-dark"] {
${cssVars}
}

:root {
${cssVars}
}
`;
      },

      // Custom format for TailwindCSS preset
      'tailwind/preset': ({ dictionary }) => {
        const tokens = dictionary.allTokens;

        // Group tokens by category
        const grouped = tokens.reduce((acc, token) => {
          const category = token.path[0];
          if (!acc[category]) acc[category] = {};

          const path = token.path.slice(1);
          let current = acc[category];

          for (let i = 0; i < path.length - 1; i++) {
            if (!current[path[i]]) current[path[i]] = {};
            current = current[path[i]];
          }

          current[path[path.length - 1]] = `var(--v-${token.path.join('-')})`;
          return acc;
        }, {});

        return `/**
 * VNext TailwindCSS Preset
 * Generated by Style Dictionary
 * DO NOT EDIT MANUALLY
 */

export default {
  theme: {
    extend: {
      colors: {
        v: ${JSON.stringify(grouped.color || {}, null, 6)},
      },
      spacing: {
        v: ${JSON.stringify(grouped.space || {}, null, 6)},
      },
      fontFamily: {
        v: ${JSON.stringify(grouped.font?.family || {}, null, 6)},
      },
      fontSize: {
        v: ${JSON.stringify(grouped.font?.size || {}, null, 6)},
      },
      fontWeight: {
        v: ${JSON.stringify(grouped.font?.weight || {}, null, 6)},
      },
      lineHeight: {
        v: ${JSON.stringify(grouped.font?.lineHeight || {}, null, 6)},
      },
      letterSpacing: {
        v: ${JSON.stringify(grouped.font?.letterSpacing || {}, null, 6)},
      },
      boxShadow: {
        v: ${JSON.stringify(grouped.shadow || {}, null, 6)},
      },
      borderRadius: {
        v: ${JSON.stringify(grouped.radius || {}, null, 6)},
      },
    },
  },
};
`;
      },
    },
  },
};
